
namespace :css do
  desc "Build countries flags css"
  task :countries do
    File.open("src/flags.authy.css", "w") do |f|
      f.puts "// THIS FILE IS AUTOGENERATED. PLEASE DO NOT MODIFIED IT"
      Dir["src/images/flags/*.gif"].each do |flag|
        name = File.basename(flag, ".gif")
        f.puts ".flag_#{name} { background: url('images/flags/#{name}.gif') no-repeat 0px center; }"
      end
      f.puts ".aflag { width: 16px; height: 12px; display: inline-block;}"
    end
  end

  desc "Compile"
  task :compile => ["css:countries"] do
    system "cat src/flags.authy.css src/form.authy.css | yuicompressor --type css -o src/form.authy.min.css"
  end
end


namespace :js do
  desc "Compile"
  task :compile do
    system "cat src/form.authy.js | yuicompressor --type js -o src/form.authy.min.js"
  end
end

task :compile => ["css:compile", "js:compile"] do
end

task :package => ["compile"] do
  puts "Generating form.authy.zip ..."
  system "cd src; zip form.authy.zip form.authy.min.js form.authy.min.css images/**/*; mv form.authy.zip .."
end

task :default => :compile